name: Deploy Nuxt to Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Забираем код из репозитория.
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Логинимся в Docker Hub (для публикации образа)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Шаг 3: Собираем и пушим Docker-образ
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/nuxtjs-app:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nuxtjs-app:latest

      # Сборка образа и отправка на сервер
      - name: Build and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop nuxtjs-app || true
            docker rm nuxtjs-app || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/nuxtjs-app:latest
            docker run -d --name nuxtjs-app -p 3000:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/nuxtjs-app:latest
